# Generated by Django 3.1.3 on 2021-10-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Имя и Фамилия')),
                ('content', models.CharField(blank=True, max_length=300, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('photo', models.ImageField(blank='True', upload_to='photos/%y/%m/%d/', verbose_name='Фотография')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published?')),
                ('views', models.IntegerField(default=0)),
                ('facebook', models.URLField(default='https://www.facebook.com/reputation.moscow', max_length=300, verbose_name='Ссылка на фейсбук')),
                ('telegram', models.CharField(default='https://t.me/reputation_moscow', max_length=300, verbose_name='Ссылка на Телеграм')),
                ('twitter', models.URLField(default='https://twitter.com/reputation_msk', max_length=300, verbose_name='Ссылка на Твиттер')),
                ('youtube', models.URLField(default='https://www.youtube.com/channel/UCO5ByGg4jQZbIjvxvTrGHXA', max_length=300, verbose_name='Ссылка на Ютуб')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.author', verbose_name='Почта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
