# Generated by Django 3.1.3 on 2021-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211015_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['title'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Подпись', 'verbose_name_plural': 'Подписи'},
        ),
        migrations.AddField(
            model_name='news',
            name='photoUrl',
            field=models.URLField(default='https://reputation.moscow/wp-content/uploads/2021/10/tpt4wah34-ur3adchsq-0842468d74a9-512-3.png', max_length=300, verbose_name='Ссылка на круглую фотографию размером 120x120'),
        ),
    ]
